[pytest]
testpaths = tests
addopts = --alluredir=reports/allure-results --html=reports/report.html --self-contained-html
markers =
    smoke: Vigtigste tests der verificerer kernefunktionalitet
    regression: Alle tests der køres ved regression
    negative: Tests der verificerer fejlhåndtering og ugyldige inputs